/**
 * Swagger QuikOpp
 * This is the swagger API for QuikOpp
 *
 * OpenAPI spec version: 1.0.0
 * Contact: qreateinc@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Address model module.
* @module model/Address
* @version 1.0.0
*/
export default class Address {
    /**
    * Constructs a new <code>Address</code>.
    * @alias module:model/Address
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Address</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Address} obj Optional instance to populate.
    * @return {module:model/Address} The populated <code>Address</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Address();
                        
            
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('province')) {
                obj['province'] = ApiClient.convertToType(data['province'], 'String');
            }
            if (data.hasOwnProperty('street')) {
                obj['street'] = ApiClient.convertToType(data['street'], 'String');
            }
            if (data.hasOwnProperty('streetNumber')) {
                obj['streetNumber'] = ApiClient.convertToType(data['streetNumber'], 'String');
            }
            if (data.hasOwnProperty('postalCode')) {
                obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
            }
            if (data.hasOwnProperty('longtitude')) {
                obj['longtitude'] = ApiClient.convertToType(data['longtitude'], 'String');
            }
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} city
    */
    'city' = undefined;
    /**
    * @member {String} province
    */
    'province' = undefined;
    /**
    * @member {String} street
    */
    'street' = undefined;
    /**
    * @member {String} streetNumber
    */
    'streetNumber' = undefined;
    /**
    * @member {String} postalCode
    */
    'postalCode' = undefined;
    /**
    * @member {String} longtitude
    */
    'longtitude' = undefined;
    /**
    * @member {String} latitude
    */
    'latitude' = undefined;




}
