/**
 * Swagger QuikOpp
 * This is the swagger API for QuikOpp
 *
 * OpenAPI spec version: 1.0.0
 * Contact: qreateinc@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Candidate model module.
* @module model/Candidate
* @version 1.0.0
*/
export default class Candidate {
    /**
    * Constructs a new <code>Candidate</code>.
    * @alias module:model/Candidate
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Candidate</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Candidate} obj Optional instance to populate.
    * @return {module:model/Candidate} The populated <code>Candidate</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Candidate();
                        
            
            if (data.hasOwnProperty('headline')) {
                obj['headline'] = ApiClient.convertToType(data['headline'], 'String');
            }
            if (data.hasOwnProperty('blurb')) {
                obj['blurb'] = ApiClient.convertToType(data['blurb'], 'String');
            }
            if (data.hasOwnProperty('hourlyRate')) {
                obj['hourlyRate'] = ApiClient.convertToType(data['hourlyRate'], 'Number');
            }
            if (data.hasOwnProperty('lookingFor')) {
                obj['lookingFor'] = ApiClient.convertToType(data['lookingFor'], 'String');
            }
            if (data.hasOwnProperty('shift')) {
                obj['shift'] = ApiClient.convertToType(data['shift'], 'String');
            }
            if (data.hasOwnProperty('skillCategory')) {
                obj['skillCategory'] = ApiClient.convertToType(data['skillCategory'], ['String']);
            }
            if (data.hasOwnProperty('skillSet')) {
                obj['skillSet'] = ApiClient.convertToType(data['skillSet'], ['String']);
            }
        }
        return obj;
    }

    /**
    * up to 100 characters
    * @member {String} headline
    */
    'headline' = undefined;
    /**
    * up to 5000 characters
    * @member {String} blurb
    */
    'blurb' = undefined;
    /**
    * round to dollar
    * @member {Number} hourlyRate
    */
    'hourlyRate' = undefined;
    /**
    * @member {module:model/Candidate.LookingForEnum} lookingFor
    */
    'lookingFor' = undefined;
    /**
    * Day or Night + 1, 2, 3, 4, 5, 6, 7  in csv format
    * @member {String} shift
    */
    'shift' = undefined;
    /**
    * list from a ref table or enum
    * @member {Array.<String>} skillCategory
    */
    'skillCategory' = undefined;
    /**
    * list from a ref table or enum
    * @member {Array.<String>} skillSet
    */
    'skillSet' = undefined;



    /**
    * Allowed values for the <code>lookingFor</code> property.
    * @enum {String}
    * @readonly
    */
    static LookingForEnum = {
        /**
         * value: "PartTime"
         * @const
         */
        "PartTime": "PartTime",
        /**
         * value: "Contract"
         * @const
         */
        "Contract": "Contract"    };

}
