/**
 * Swagger QuikOpp
 * This is the swagger API for QuikOpp
 *
 * OpenAPI spec version: 1.0.0
 * Contact: qreateinc@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';

/**
* The Company model module.
* @module model/Company
* @version 1.0.0
*/
export default class Company {
    /**
    * Constructs a new <code>Company</code>.
    * @alias module:model/Company
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Company</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Company} obj Optional instance to populate.
    * @return {module:model/Company} The populated <code>Company</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Company();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('industry')) {
                obj['industry'] = ApiClient.convertToType(data['industry'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = Address.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('companyId')) {
                obj['companyId'] = ApiClient.convertToType(data['companyId'], 'String');
            }
            if (data.hasOwnProperty('associatedUserId')) {
                obj['associatedUserId'] = ApiClient.convertToType(data['associatedUserId'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} description
    */
    'description' = undefined;
    /**
    * @member {module:model/Company.IndustryEnum} industry
    */
    'industry' = undefined;
    /**
    * @member {String} phone
    */
    'phone' = undefined;
    /**
    * @member {module:model/Address} address
    */
    'address' = undefined;
    /**
    * company id to identify job post
    * @member {String} companyId
    */
    'companyId' = undefined;
    /**
    * userId of the user who setup employer profile
    * @member {String} associatedUserId
    */
    'associatedUserId' = undefined;



    /**
    * Allowed values for the <code>industry</code> property.
    * @enum {String}
    * @readonly
    */
    static IndustryEnum = {
        /**
         * value: "Food"
         * @const
         */
        "Food": "Food",
        /**
         * value: "IT"
         * @const
         */
        "IT": "IT"    };

}
