/**
 * Swagger QuikOpp
 * This is the swagger API for QuikOpp
 *
 * OpenAPI spec version: 1.0.0
 * Contact: qreateinc@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The History model module.
* @module model/History
* @version 1.0.0
*/
export default class History {
    /**
    * Constructs a new <code>History</code>.
    * @alias module:model/History
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>History</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/History} obj Optional instance to populate.
    * @return {module:model/History} The populated <code>History</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new History();
                        
            
            if (data.hasOwnProperty('jobId')) {
                obj['jobId'] = ApiClient.convertToType(data['jobId'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} jobId
    */
    'jobId' = undefined;
    /**
    * @member {String} status
    */
    'status' = undefined;
    /**
    * @member {String} date
    */
    'date' = undefined;




}
