/**
 * Swagger QuikOpp
 * This is the swagger API for QuikOpp
 *
 * OpenAPI spec version: 1.0.0
 * Contact: qreateinc@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerQuikOpp);
  }
}(this, function(expect, SwaggerQuikOpp) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerQuikOpp.Candidate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Candidate', function() {
    it('should create an instance of Candidate', function() {
      // uncomment below and update the code to test Candidate
      //var instane = new SwaggerQuikOpp.Candidate();
      //expect(instance).to.be.a(SwaggerQuikOpp.Candidate);
    });

    it('should have the property headline (base name: "headline")', function() {
      // uncomment below and update the code to test the property headline
      //var instane = new SwaggerQuikOpp.Candidate();
      //expect(instance).to.be();
    });

    it('should have the property blurb (base name: "blurb")', function() {
      // uncomment below and update the code to test the property blurb
      //var instane = new SwaggerQuikOpp.Candidate();
      //expect(instance).to.be();
    });

    it('should have the property hourlyRate (base name: "hourlyRate")', function() {
      // uncomment below and update the code to test the property hourlyRate
      //var instane = new SwaggerQuikOpp.Candidate();
      //expect(instance).to.be();
    });

    it('should have the property lookingFor (base name: "lookingFor")', function() {
      // uncomment below and update the code to test the property lookingFor
      //var instane = new SwaggerQuikOpp.Candidate();
      //expect(instance).to.be();
    });

    it('should have the property shift (base name: "shift")', function() {
      // uncomment below and update the code to test the property shift
      //var instane = new SwaggerQuikOpp.Candidate();
      //expect(instance).to.be();
    });

    it('should have the property skillCategory (base name: "skillCategory")', function() {
      // uncomment below and update the code to test the property skillCategory
      //var instane = new SwaggerQuikOpp.Candidate();
      //expect(instance).to.be();
    });

    it('should have the property skillSet (base name: "skillSet")', function() {
      // uncomment below and update the code to test the property skillSet
      //var instane = new SwaggerQuikOpp.Candidate();
      //expect(instance).to.be();
    });

  });

}));
