/**
 * Swagger QuikOpp
 * This is the swagger API for QuikOpp
 *
 * OpenAPI spec version: 1.0.0
 * Contact: qreateinc@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerQuikOpp);
  }
}(this, function(expect, SwaggerQuikOpp) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerQuikOpp.Job();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Job', function() {
    it('should create an instance of Job', function() {
      // uncomment below and update the code to test Job
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be.a(SwaggerQuikOpp.Job);
    });

    it('should have the property jobID (base name: "jobID")', function() {
      // uncomment below and update the code to test the property jobID
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be();
    });

    it('should have the property companyId (base name: "companyId")', function() {
      // uncomment below and update the code to test the property companyId
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be();
    });

    it('should have the property headline (base name: "headline")', function() {
      // uncomment below and update the code to test the property headline
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be();
    });

    it('should have the property jobDescription (base name: "jobDescription")', function() {
      // uncomment below and update the code to test the property jobDescription
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be();
    });

    it('should have the property jobType (base name: "jobType")', function() {
      // uncomment below and update the code to test the property jobType
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be();
    });

    it('should have the property shiftPeriod (base name: "shiftPeriod")', function() {
      // uncomment below and update the code to test the property shiftPeriod
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be();
    });

    it('should have the property shiftStartTime (base name: "shiftStartTime")', function() {
      // uncomment below and update the code to test the property shiftStartTime
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be();
    });

    it('should have the property shiftEndTime (base name: "shiftEndTime")', function() {
      // uncomment below and update the code to test the property shiftEndTime
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be();
    });

    it('should have the property skillCategory (base name: "skillCategory")', function() {
      // uncomment below and update the code to test the property skillCategory
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be();
    });

    it('should have the property skillSet (base name: "skillSet")', function() {
      // uncomment below and update the code to test the property skillSet
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be();
    });

    it('should have the property appliedCandidates (base name: "appliedCandidates")', function() {
      // uncomment below and update the code to test the property appliedCandidates
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be();
    });

    it('should have the property acceptedCandidate (base name: "acceptedCandidate")', function() {
      // uncomment below and update the code to test the property acceptedCandidate
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be();
    });

    it('should have the property feedback (base name: "feedback")', function() {
      // uncomment below and update the code to test the property feedback
      //var instane = new SwaggerQuikOpp.Job();
      //expect(instance).to.be();
    });

  });

}));
